server:
  port: 8092

spring:

  #MySQL
  datasource:
    druid:
      url: jdbc:p6spy:mysql://localhost:3306/study_new?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: zzm246810
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver


  #Redis
  redis:
    host: 127.0.0.1
    port: 6379
    password: admin123
    lettuce:
      pool:
        max-active: 50
        max-wait: 3000ms
        max-idle: 50
        min-idle: 3
    connect-timeout: 30000
    database: 11


  # 模板引擎
  thymeleaf:
    # 开发时关闭缓存不然没法看到实时页面
    cache: false
    # 启用不严格检查
    mode: LEGACYHTML5
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration


  # 指定路径匹配规则
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


# mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
  type-aliases-package: com.example.manage.entity

#j2cache
j2cache:
  config-location: classpath:/j2cache-${spring.profiles.active}.properties
  open-spring-cache: true
  redis-client: lettuce


# Elasticsearch配置
elasticsearch:
  hostname: 192.168.0.108
  port: 9200


#配置swagger配置
knife4j:
  basic:
    username: admin
    password: 123
    enable: false #开启认证
  production: false #默认是false ,屏蔽所有Swagger的相关资源
  enable: true #是否开启swagger


# 自定义jwt的header
zzm:
  jwt:
    header: Authorization
    expire: 604800 # 7天，s为单位
    secret: abcdefghabcdefghabcdefghabcdefgh