server:
  port: 8888

spring:

  #MySQL
  datasource:
    druid:
      url: jdbc:p6spy:mysql://localhost:3306/new_study?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: 123456
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver


  #Redis
  redis:
    host: 127.0.0.1
    port: 6379
    password: admin123
    lettuce:
      pool:
        max-active: 50      #连接池最大连接数（使用负值表示没有限制）
        max-wait: 3000ms    #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 50        #连接池中的最大空闲连接
        min-idle: 3        #连接池中的最小空闲连接
    connect-timeout: 30000 #连接超时时间（毫秒）
    database: 11


# mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    banner: false
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
  type-aliases-package: com.example.manage.entity


#j2cache
j2cache:
  config-location: classpath:/j2cache-${spring.profiles.active}.properties
  open-spring-cache: true
  redis-client: lettuce
