server:
  port: 8848
  tomcat:
    uri-encoding: UTF-8
spring:
  banner:
    charset: UTF-8
  messages:
    encoding: UTF-8
  datasource:
    url: jdbc:mysql://localhost:3306/springboot-Thymeleaf?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false